// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UNIOOP.App.Data;

#nullable disable

namespace UniOOP.App.Migrations
{
    [DbContext(typeof(DataContextEF))]
    [Migration("20260826143148_AddUserAccount")]
    partial class AddUserAccount
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UNIOOP.App.Models.Course", b =>
                {
                    b.Property<int>("CourseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CourseID"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("course_name");

                    b.Property<short>("Credits")
                        .HasColumnType("smallint")
                        .HasColumnName("credits");

                    b.Property<long?>("TeacherPersonnelID")
                        .HasColumnType("bigint")
                        .HasColumnName("teacher_personnel_id");

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.HasKey("CourseID")
                        .HasName("PK_Course");

                    b.HasIndex("TeacherPersonnelID")
                        .HasDatabaseName("IX_Course_TeacherPersonnelID");

                    b.HasIndex("UniversityID")
                        .HasDatabaseName("IX_Course_UniversityID");

                    b.HasIndex("UniversityID", "CourseName")
                        .IsUnique()
                        .HasDatabaseName("UX_Course_UniversityID_CourseName");

                    b.ToTable("Course", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Course_Credits", "credits BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("UNIOOP.App.Models.Personnel", b =>
                {
                    b.Property<long>("PersonnelID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("personnel_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PersonnelID"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("f_name");

                    b.Property<string>("LName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("l_name");

                    b.Property<string>("SSN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ssn");

                    b.HasKey("PersonnelID");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Personnel_Email");

                    b.HasIndex("SSN")
                        .IsUnique()
                        .HasDatabaseName("UX_Personnel_SSN");

                    b.ToTable("Personnel", "public");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("UNIOOP.App.Models.StudentCourse", b =>
                {
                    b.Property<long>("StudentPersonnelID")
                        .HasColumnType("bigint")
                        .HasColumnName("student_personnel_id");

                    b.Property<int>("CourseID")
                        .HasColumnType("integer")
                        .HasColumnName("course_id");

                    b.HasKey("StudentPersonnelID", "CourseID")
                        .HasName("PK_StudentCourse");

                    b.HasIndex("CourseID")
                        .HasDatabaseName("IX_StudentCourse_CourseID");

                    b.ToTable("StudentCourse", "public");
                });

            modelBuilder.Entity("UNIOOP.App.Models.University", b =>
                {
                    b.Property<int>("UniversityID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UniversityID"));

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("university_name");

                    b.HasKey("UniversityID")
                        .HasName("PK_University");

                    b.HasIndex("UniversityName")
                        .IsUnique()
                        .HasDatabaseName("UX_University_UniversityName");

                    b.ToTable("University", "public");
                });

            modelBuilder.Entity("UNIOOP.App.Models.UserAccount", b =>
                {
                    b.Property<int>("UserAccountID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_account_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserAccountID"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<long?>("PersonnelID")
                        .HasColumnType("bigint")
                        .HasColumnName("personnel_id");

                    b.Property<int?>("UniversityID")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.Property<int>("UserType")
                        .HasColumnType("integer")
                        .HasColumnName("user_type");

                    b.HasKey("UserAccountID")
                        .HasName("pk_user_account");

                    b.HasIndex("PersonnelID")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_personnel_id");

                    b.HasIndex("UniversityID")
                        .IsUnique()
                        .HasDatabaseName("ix_user_account_university_id");

                    b.ToTable("UserAccount", "public", t =>
                        {
                            t.HasCheckConstraint("CK_UserAccount_ExactlyOneOwner", "(\"personnel_id\" IS NOT NULL AND \"university_id\" IS NULL) OR (\"personnel_id\" IS NULL AND \"university_id\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("UNIOOP.App.Models.GovernmentOfficer", b =>
                {
                    b.HasBaseType("UNIOOP.App.Models.Personnel");

                    b.Property<int>("OfficerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("officer_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OfficerID"));

                    b.HasIndex("OfficerID")
                        .IsUnique()
                        .HasDatabaseName("UX_GovernmentOfficer_OfficerID");

                    b.ToTable("GovernmentOfficer", "public");
                });

            modelBuilder.Entity("UNIOOP.App.Models.Student", b =>
                {
                    b.HasBaseType("UNIOOP.App.Models.Personnel");

                    b.Property<decimal>("GPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("gpa");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("major");

                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("student_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentID"));

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.HasIndex("StudentID")
                        .IsUnique()
                        .HasDatabaseName("UX_Student_StudentID");

                    b.HasIndex("UniversityID")
                        .HasDatabaseName("IX_Student_UniversityID");

                    b.ToTable("Student", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Student_GPA", "\"gpa\" >= 0.00 AND \"gpa\" <= 4.00");
                        });
                });

            modelBuilder.Entity("UNIOOP.App.Models.Teacher", b =>
                {
                    b.HasBaseType("UNIOOP.App.Models.Personnel");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("department");

                    b.Property<int?>("MinistryDegreeID")
                        .HasColumnType("integer")
                        .HasColumnName("ministry_degree_id");

                    b.Property<decimal>("Salary")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary");

                    b.Property<int>("TeacherID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("teacher_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TeacherID"));

                    b.Property<int>("UniversityID")
                        .HasColumnType("integer")
                        .HasColumnName("university_id");

                    b.HasIndex("TeacherID")
                        .IsUnique()
                        .HasDatabaseName("UX_Teacher_TeacherID");

                    b.HasIndex("UniversityID")
                        .HasDatabaseName("IX_Teacher_UniversityID");

                    b.ToTable("Teacher", "public", t =>
                        {
                            t.HasCheckConstraint("CK_Teachert_Salary", "\"salary\" >= 0 ");
                        });
                });

            modelBuilder.Entity("UNIOOP.App.Models.Course", b =>
                {
                    b.HasOne("UNIOOP.App.Models.Teacher", "Teacher")
                        .WithMany("coursesCollection")
                        .HasForeignKey("TeacherPersonnelID")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Course_Teacher");

                    b.HasOne("UNIOOP.App.Models.University", "University")
                        .WithMany("coursesCollection")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Course_University");

                    b.Navigation("Teacher");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UNIOOP.App.Models.StudentCourse", b =>
                {
                    b.HasOne("UNIOOP.App.Models.Course", "Course")
                        .WithMany("enrollmentCollection")
                        .HasForeignKey("CourseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentCourse_Course");

                    b.HasOne("UNIOOP.App.Models.Student", "Student")
                        .WithMany("enrollmentCollection")
                        .HasForeignKey("StudentPersonnelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_StudentCourse_Student");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UNIOOP.App.Models.UserAccount", b =>
                {
                    b.HasOne("UNIOOP.App.Models.Personnel", "Personnel")
                        .WithOne()
                        .HasForeignKey("UNIOOP.App.Models.UserAccount", "PersonnelID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_account_personnel_personnel_id");

                    b.HasOne("UNIOOP.App.Models.University", "University")
                        .WithOne()
                        .HasForeignKey("UNIOOP.App.Models.UserAccount", "UniversityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_user_account_university_university_id");

                    b.Navigation("Personnel");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UNIOOP.App.Models.GovernmentOfficer", b =>
                {
                    b.HasOne("UNIOOP.App.Models.Personnel", null)
                        .WithOne()
                        .HasForeignKey("UNIOOP.App.Models.GovernmentOfficer", "PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_government_officer_personnel_personnel_id");
                });

            modelBuilder.Entity("UNIOOP.App.Models.Student", b =>
                {
                    b.HasOne("UNIOOP.App.Models.Personnel", null)
                        .WithOne()
                        .HasForeignKey("UNIOOP.App.Models.Student", "PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_personnel_personnel_id");

                    b.HasOne("UNIOOP.App.Models.University", "University")
                        .WithMany("studentsCollection")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Student_University");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UNIOOP.App.Models.Teacher", b =>
                {
                    b.HasOne("UNIOOP.App.Models.Personnel", null)
                        .WithOne()
                        .HasForeignKey("UNIOOP.App.Models.Teacher", "PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_teacher_personnel_personnel_id");

                    b.HasOne("UNIOOP.App.Models.University", "University")
                        .WithMany("teachersCollection")
                        .HasForeignKey("UniversityID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Teacher_University");

                    b.Navigation("University");
                });

            modelBuilder.Entity("UNIOOP.App.Models.Course", b =>
                {
                    b.Navigation("enrollmentCollection");
                });

            modelBuilder.Entity("UNIOOP.App.Models.University", b =>
                {
                    b.Navigation("coursesCollection");

                    b.Navigation("studentsCollection");

                    b.Navigation("teachersCollection");
                });

            modelBuilder.Entity("UNIOOP.App.Models.Student", b =>
                {
                    b.Navigation("enrollmentCollection");
                });

            modelBuilder.Entity("UNIOOP.App.Models.Teacher", b =>
                {
                    b.Navigation("coursesCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
